all_vms:
  hosts:
    master_vm:
      ansible_host: 192.168.122.10
    worker_vm1:
      ansible_host: 192.168.122.20
    worker_vm2:
      ansible_host: 192.168.121.30
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') }}" 
